# Generated by Django 5.1.5 on 2026-01-19 09:19

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=encrypted_model_fields.fields.EncryptedCharField(unique=True, verbose_name='CPF'),
        ),
    ]
