# Generated by Django 5.1.5 on 2026-01-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0002_alter_pessoa_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissoesGerais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('pode_ver_configuracoes', 'Pode acessar as configurações do sistema'), ('pode_fazer_backup', 'Pode realizar e baixar backups')],
                'managed': False,
            },
        ),
    ]
