# Generated by Django 5.1.5 on 2026-01-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0003_permissoesgerais'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficio',
            name='icone',
            field=models.CharField(choices=[('bi-bus-front', 'Ônibus'), ('bi-cash-coin', 'Moeda'), ('bi-wallet2', 'Carteira'), ('bi-currency-dollar', 'Cifrão'), ('bi-piggy-bank', 'Cofrinho'), ('bi-heart-pulse', 'Saúde')], default='bi-wallet2', max_length=30),
        ),
    ]
