# Generated by Django 5.1.5 on 2026-01-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0004_beneficio_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='bairro',
            field=models.CharField(default='Centro', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='celular',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cidade',
            field=models.CharField(choices=[('Pocinhos/PB', 'Pocinhos/PB')], default='Pocinhos/PB', max_length=50),
            preserve_default=False,
        ),
    ]
