# Generated by Django 5.1.5 on 2026-01-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0005_pessoa_bairro_pessoa_celular_pessoa_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficio',
            name='icone',
            field=models.CharField(choices=[('bi-bus-front', 'Ônibus'), ('bi-cash-coin', 'Moeda'), ('bi-wallet2', 'Carteira'), ('bi-currency-dollar', 'Cifrão'), ('bi-cart', 'Mercado'), ('bi-heart-pulse', 'Saúde')], default='bi-wallet2', max_length=30),
        ),
    ]
