# Generated by Django 5.1.5 on 2026-01-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0006_alter_beneficio_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficio',
            name='icone',
            field=models.CharField(choices=[('bi-bus-front', 'Ônibus'), ('bi-cash-coin', 'Moeda'), ('bi-calendar-event', 'Único'), ('bi-hourglass-split', 'Temporário'), ('bi-cart', 'Mercado'), ('bi-heart-pulse', 'Saúde')], default='bi-wallet2', max_length=30),
        ),
    ]
