# Generated by Django 5.1.5 on 2026-01-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0007_alter_beneficio_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cpf_ultimos_4',
            field=models.CharField(blank=True, db_index=True, default='', max_length=4),
        ),
    ]
