# Generated by Django 5.1.5 on 2026-02-06 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0009_alter_pessoa_data_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=12, unique=True)),
                ('ano', models.PositiveIntegerField()),
                ('sequencia', models.PositiveIntegerField()),
                ('conta_pagadora', models.CharField(blank=True, max_length=200)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantidade_pessoas', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='beneficios.beneficio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Memorando',
                'verbose_name_plural': 'Memorandos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemorandoPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
                ('valor_beneficio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordem', models.PositiveIntegerField()),
                ('memorando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='beneficios.memorando')),
                ('pessoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficios.pessoa')),
            ],
            options={
                'verbose_name': 'Pessoa do Memorando',
                'verbose_name_plural': 'Pessoas do Memorando',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddConstraint(
            model_name='memorando',
            constraint=models.UniqueConstraint(fields=('ano', 'sequencia'), name='unique_sequencia_ano'),
        ),
    ]
