# Generated by Django 5.1.5 on 2026-02-07 01:50

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0010_memorando_memorandopessoa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorandopessoa',
            name='cpf',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
