# Generated by Django 5.1.5 on 2026-02-07 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0011_encrypt_cpf_memorandopessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorandopessoa',
            name='cpf',
        ),
    ]
