# Generated by Django 5.1.5 on 2026-02-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0012_remove_cpf_memorandopessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretaria_nome', models.CharField(default='Zélia Maria Matias e Silva', max_length=100, verbose_name='Nome do(a) Secretário(a)')),
                ('secretaria_cargo', models.CharField(default='Secretária Adjunta de Assistência Social', max_length=100, verbose_name='Cargo')),
                ('financas_nome', models.CharField(default='Carlos Roberto Alves Filho', max_length=100, verbose_name='Nome do Secretário de Finanças')),
                ('financas_cargo', models.CharField(default='Secretário de Finanças', max_length=100, verbose_name='Cargo')),
                ('email_institucional', models.EmailField(default='assistenciasocialpocinhos@gmail.com', max_length=254, verbose_name='E-mail institucional')),
                ('endereco', models.CharField(default='Rua Pç. Pres. Getúlio Vargas, 57, Centro', max_length=200, verbose_name='Endereço')),
                ('cep', models.CharField(default='58150-000', max_length=10, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Configuração Geral',
                'verbose_name_plural': 'Configurações Gerais',
            },
        ),
    ]
