# Generated by Django 5.1.5 on 2026-02-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0013_configuracao_geral'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorando',
            name='cep',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='memorando',
            name='email_institucional',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='memorando',
            name='endereco',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='memorando',
            name='financas_cargo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='memorando',
            name='financas_nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='memorando',
            name='secretaria_cargo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='memorando',
            name='secretaria_nome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
