# Generated by Django 5.1.5 on 2026-02-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0014_memorando_config_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True, verbose_name='Deve trocar senha'),
        ),
    ]
