# Generated by Django 5.1.5 on 2026-03-07 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0015_user_must_change_password'),
        ('beneficios', '0018_remove_pessoa_ativo'),
    ]

    operations = [
    ]
