# Generated by Django 5.1.5 on 2026-03-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0019_merge_20260306_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='valor_beneficio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
