# Generated by Django 5.1.5 on 2026-03-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0020_alter_pessoa_valor_beneficio'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficio',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Descrição'),
        ),
    ]
