# Generated by Django 5.1.5 on 2026-03-10 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0021_beneficio_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('memorando_individual', 'Memorando Individual'), ('memorando_massa', 'Memorando em Massa'), ('recibo_individual', 'Recibo Individual'), ('recibos_massa', 'Recibos em Massa'), ('documentos_massa', 'Documentos em Massa'), ('remessa_banco', 'Arquivo Remessa'), ('relatorio_beneficiarios_pdf', 'Relatório Beneficiários PDF'), ('relatorio_beneficiarios_xlsx', 'Relatório Beneficiários Excel'), ('relatorio_financeiro_pdf', 'Relatório Financeiro PDF'), ('relatorio_financeiro_xlsx', 'Relatório Financeiro Excel'), ('status_ativar', 'Ativou Pessoa'), ('status_espera', 'Moveu para Espera'), ('status_desligar', 'Desligou Pessoa')], max_length=50)),
                ('descricao', models.TextField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Ação',
                'verbose_name_plural': 'Logs de Ações',
                'ordering': ['-created_at'],
            },
        ),
    ]
