# Generated by Django 5.1.5 on 2026-03-11 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0022_logacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rclone_nome_remote', models.CharField(default='DRIVE', max_length=100, verbose_name='Nome do remote rclone')),
                ('rclone_pasta', models.CharField(default='BackupGESOCIAL', max_length=200, verbose_name='Pasta de destino')),
                ('agendamento_ativo', models.BooleanField(default=False, verbose_name='Agendamento ativo')),
                ('horario', models.TimeField(default='03:00', verbose_name='Horário')),
                ('frequencia', models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal')], default='diario', max_length=10, verbose_name='Frequência')),
                ('incluir_banco', models.BooleanField(default=True, verbose_name='Banco de dados')),
                ('incluir_documentos', models.BooleanField(default=True, verbose_name='Documentos')),
                ('incluir_configs', models.BooleanField(default=True, verbose_name='Configurações')),
                ('versoes_nuvem', models.PositiveIntegerField(default=5, verbose_name='Versões na nuvem')),
                ('versoes_local', models.PositiveIntegerField(default=5, verbose_name='Versões locais')),
            ],
            options={
                'verbose_name': 'Configuração de Backup',
                'verbose_name_plural': 'Configurações de Backup',
            },
        ),
        migrations.CreateModel(
            name='BackupHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático')], max_length=15)),
                ('tamanho_bytes', models.BigIntegerField(blank=True, null=True)),
                ('itens', models.CharField(max_length=100, verbose_name='Itens incluídos')),
                ('status', models.CharField(choices=[('executando', 'Executando'), ('sucesso', 'Sucesso'), ('erro', 'Erro')], default='executando', max_length=15)),
                ('arquivo_nome', models.CharField(blank=True, default='', max_length=200)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Backup',
                'verbose_name_plural': 'Históricos de Backup',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('inicio', 'Início'), ('dump_banco', 'Dump do Banco'), ('compactar_docs', 'Compactar Documentos'), ('compactar_configs', 'Compactar Configurações'), ('comprimir', 'Comprimir (zstd)'), ('criptografar', 'Criptografar (GPG)'), ('copiar_local', 'Copiar Local'), ('enviar', 'Enviar Google Drive'), ('retencao_nuvem', 'Retenção Nuvem'), ('retencao_local', 'Retenção Local'), ('limpar', 'Limpeza Temporários'), ('fim', 'Finalização')], max_length=30)),
                ('status', models.CharField(choices=[('executando', 'Executando'), ('sucesso', 'Sucesso'), ('erro', 'Erro')], max_length=15)),
                ('mensagem', models.TextField(blank=True, default='')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='beneficios.backuphistorico')),
            ],
            options={
                'verbose_name': 'Log de Backup',
                'verbose_name_plural': 'Logs de Backup',
                'ordering': ['data'],
            },
        ),
    ]
