# Generated by Django 5.1.5 on 2026-03-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0023_backupconfig_backuphistorico_backuplog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupconfig',
            name='agendamento_ativo',
        ),
        migrations.RemoveField(
            model_name='backupconfig',
            name='frequencia',
        ),
        migrations.RemoveField(
            model_name='backupconfig',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='backupconfig',
            name='incluir_banco',
        ),
        migrations.RemoveField(
            model_name='backupconfig',
            name='incluir_configs',
        ),
        migrations.RemoveField(
            model_name='backupconfig',
            name='incluir_documentos',
        ),
        migrations.RemoveField(
            model_name='backupconfig',
            name='versoes_local',
        ),
        migrations.RemoveField(
            model_name='backupconfig',
            name='versoes_nuvem',
        ),
        migrations.AddField(
            model_name='backupconfig',
            name='agendamento_db_ativo',
            field=models.BooleanField(default=False, verbose_name='Agendar backup do banco'),
        ),
        migrations.AddField(
            model_name='backupconfig',
            name='agendamento_doc_ativo',
            field=models.BooleanField(default=False, verbose_name='Agendar backup de documentos'),
        ),
        migrations.AddField(
            model_name='backupconfig',
            name='frequencia_db',
            field=models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal')], default='diario', max_length=10, verbose_name='Frequência (Banco)'),
        ),
        migrations.AddField(
            model_name='backupconfig',
            name='frequencia_doc',
            field=models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal')], default='semanal', max_length=10, verbose_name='Frequência (Documentos)'),
        ),
        migrations.AddField(
            model_name='backupconfig',
            name='horario_db',
            field=models.TimeField(default='03:00', verbose_name='Horário (Banco)'),
        ),
        migrations.AddField(
            model_name='backupconfig',
            name='horario_doc',
            field=models.TimeField(default='04:00', verbose_name='Horário (Documentos)'),
        ),
        migrations.AddField(
            model_name='backupconfig',
            name='versoes_local_db',
            field=models.PositiveIntegerField(default=5, verbose_name='Versões locais (Banco)'),
        ),
        migrations.AddField(
            model_name='backupconfig',
            name='versoes_local_doc',
            field=models.PositiveIntegerField(default=3, verbose_name='Versões locais (Documentos)'),
        ),
        migrations.AddField(
            model_name='backupconfig',
            name='versoes_nuvem_db',
            field=models.PositiveIntegerField(default=5, verbose_name='Versões nuvem (Banco)'),
        ),
        migrations.AddField(
            model_name='backupconfig',
            name='versoes_nuvem_doc',
            field=models.PositiveIntegerField(default=3, verbose_name='Versões nuvem (Documentos)'),
        ),
        migrations.AddField(
            model_name='backuphistorico',
            name='tipo_backup',
            field=models.CharField(choices=[('banco', 'Banco de Dados'), ('documentos', 'Documentos')], default='banco', max_length=15),
        ),
        migrations.AlterField(
            model_name='backupconfig',
            name='rclone_nome_remote',
            field=models.CharField(default='DRIVE', max_length=100, verbose_name='Nome do remote'),
        ),
    ]
