# Generated by Django 5.1.5 on 2026-03-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0024_remove_backupconfig_agendamento_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupconfig',
            name='email_conta',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail da conta Google'),
        ),
    ]
