# Generated by Django 5.1.5 on 2026-03-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0025_backupconfig_email_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cargo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='user',
            name='nome_completo',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Nome Completo'),
        ),
    ]
