# Generated by Django 5.1.5 on 2026-03-15 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0026_user_cargo_user_nome_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorando',
            name='beneficio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficios.beneficio'),
        ),
    ]
