# Generated by Django 5.1.5 on 2026-03-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0027_alter_memorando_beneficio'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorando',
            name='beneficio_nome',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
